### ISSUE TITLE
single line install from tap

### ISSUE THREAD

**Issue by alixander** [terrastruct/homebrew-tap#1]
> https://github.com/zegl/extremely-linear

<img width="373" alt="Screen Shot 2022-11-22 at 6 57 11 AM" src="https://user-images.githubusercontent.com/3120367/203346426-78c33d1f-e0a2-4db2-8ac3-812c82a42760.png">

**Comment by nhooyr** [comment]
Let's rename this repo to `tap`?

**Comment by nhooyr** [comment]
Otherwise `brew install terrastruct/d2/d2` is unfortunate. Plus it'll make more sense once we have the `tstruct` CLI to name our tap just generically `tap` instead of making it `d2` specific.

**Comment by nhooyr** [comment]
Renamed.
